"""empty message

Revision ID: 76a0c64a61c4
Revises: 8ed90477971a
Create Date: 2023-01-05 03:19:31.596462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a0c64a61c4'
down_revision = '8ed90477971a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homeworld'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['terrain'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('passengers')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('terrain')

    op.drop_table('characters')
    # ### end Alembic commands ###
